---
- name: Instalaci칩n y configuraci칩n de OpenLDAP con LAM
  hosts: ldap_servers
  become: yes
  vars:
    ldap_version: "2.6.3"
    ldap_admin_password: "1234"
    base_dn: "dc=amsa,dc=udl,dc=cat"
    dc_name: "amsa"
    ldap_user: "ldap"
    ldap_group: "ldap"
    ldap_uid: 55
    ldap_gid: 55
    users:
      - { uid: 4000, gid: 5000, username: "ramon", sn: "mateo" }
      - { uid: 4001, gid: 5001, username: "manel", sn: "lopez" }
    groups:
      - { name: "programadors", gid: 5000 }
      - { name: "dissenyadors", gid: 5001 }
    path_pki: "/etc/pki/tls"

  tasks:
    - name: Instalar paquetes necesarios
      dnf:
        name:
          - cyrus-sasl-devel
          - make
          - libtool
          - autoconf
          - libtool-ltdl-devel
          - openssl-devel
          - libdb-devel
          - tar
          - gcc
          - perl
          - perl-devel
          - wget
          - vim
          - httpd
          - php
          - php-ldap
          - php-mbstring
          - php-gd
          - php-gmp
          - php-zip
        state: present

    - name: Descargar OpenLDAP
      get_url:
        url: "ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-{{ ldap_version }}.tgz"
        dest: "/tmp/openldap-{{ ldap_version }}.tgz"

    - name: Extraer OpenLDAP
      unarchive:
        src: "/tmp/openldap-{{ ldap_version }}.tgz"
        dest: "/tmp/"
        remote_src: yes

    - name: Compilar e instalar OpenLDAP
      shell: |
        cd /tmp/openldap-{{ ldap_version }}
        ./configure --prefix=/usr --sysconfdir=/etc --disable-static \
          --enable-debug --with-tls=openssl --with-cyrus-sasl --enable-dynamic \
          --enable-crypt --enable-spasswd --enable-slapd --enable-modules \
          --enable-rlookups --disable-sql --enable-ppolicy --enable-syslog
        make depend
        make
        cd contrib/slapd-modules/passwd/sha2
        make
        cd ../../../..
        make install
        cd contrib/slapd-modules/passwd/sha2
        make install
      args:
        chdir: /tmp

    - name: Crear grupo y usuario LDAP
      group:
        name: "{{ ldap_group }}"
        gid: "{{ ldap_gid }}"
        state: present

    - name: Crear usuario LDAP
      user:
        name: "{{ ldap_user }}"
        uid: "{{ ldap_uid }}"
        group: "{{ ldap_group }}"
        system: yes
        shell: /usr/sbin/nologin
        create_home: no
        home: /var/lib/openldap

    - name: Crear directorios de OpenLDAP
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ldap_user if item == '/var/lib/openldap' else 'root' }}"
        group: "{{ ldap_group }}"
        mode: "{{ '0755' if item == '/var/lib/openldap' else '0640' }}"
      loop:
        - /var/lib/openldap
        - /etc/openldap/slapd.d

    - name: Crear archivo systemd para slapd
      copy:
        dest: /etc/systemd/system/slapd.service
        content: |
          [Unit]
          Description=OpenLDAP Server Daemon
          After=syslog.target network-online.target
          Documentation=man:slapd
          Documentation=man:slapd-mdb

          [Service]
          Type=forking
          PIDFile=/var/lib/openldap/slapd.pid
          Environment="SLAPD_URLS=ldap:/// ldapi:/// ldaps:///"
          Environment="SLAPD_OPTIONS=-F /etc/openldap/slapd.d"
          ExecStart=/usr/libexec/slapd -u ldap -g ldap -h ${SLAPD_URLS} $SLAPD_OPTIONS

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644

    - name: Habilitar y arrancar slapd
      systemd:
        name: slapd
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Generar hash de contrase침a LDAP
      shell: "slappasswd -h '{SSHA512}' -s '{{ ldap_admin_password }}' -o module-load=pw-sha2.la -o module-path=/usr/local/libexec/openldap"
      register: ldap_hash
      changed_when: false

    - name: Crear archivos LDIF base y usuarios
      template:
        src: templates/slapd_base.ldif.j2
        dest: /etc/openldap/slapd.ldif
        mode: 0644
      vars:
        hash_password: "{{ ldap_hash.stdout }}"
        base_dn: "{{ base_dn }}"
        dc_name: "{{ dc_name }}"
        users: "{{ users }}"
        groups: "{{ groups }}"

    - name: Cargar configuraci칩n inicial de LDAP
      shell: "slapadd -n 0 -F /etc/openldap/slapd.d -l /etc/openldap/slapd.ldif"
      args:
        creates: /etc/openldap/slapd.d

    - name: Ajustar permisos de slapd.d
      file:
        path: /etc/openldap/slapd.d
        owner: ldap
        group: ldap
        recurse: yes

    - name: Habilitar e iniciar Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Descargar e instalar LAM
      get_url:
        url: "https://github.com/LDAPAccountManager/lam/releases/download/9.0.RC1/ldap-account-manager-9.0.RC1-0.fedora.1.noarch.rpm"
        dest: "/tmp/ldap-account-manager.rpm"

    - name: Instalar LAM
      dnf:
        name: "/tmp/ldap-account-manager.rpm"
        state: present