---
- name: Instalacion completa de OpenLDAP compilado + configuracion + LAM
  hosts: localhost
  become: yes

  tasks:
    - name: Instalar OpenLDAP
      shell: |
        sudo bash ldapserver.sh
      args:
        chdir: /opt/ansible

    - name: Python HTTP Server per passar el certificat al client
      shell: |
        cd /etc/pki/tls
        nohup python3 -m http.server 8080 &
      args:
        executable: /bin/bash